---
title: "Gráfico Tema 3"
author: "Carolina Martínez, Álvaro Cruz, Roberto Millan y Alexandra Estela Garcia"
date: "2024-02-29"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Librerías**
Cargamos las librerías que vamos a utilizar.

```{r Librerias}
library(ggplot2)
library(tidyverse)
library(plotly)
library(dplyr)
library(showtext)
```

**Importación de datos**
Cargamos en una variable los datos de la web.
```{r Datos}
#Nos aseguramos de que el enviroment esté limpio
rm(list = ls())
data <- read.csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")
```

**Modificación de variables**
Cambiamos el formato de las variables para poder manejarlas de mejor manera.

```{r Variables}
#Ponemos el formato de fecha adecuado
data$date <- as.Date(data$date, format = "%Y-%m-%d")

#Creamos un vector con los paises que queremos representar
paises <- c("Spain","Italy", "Germany","Canada","United States",
            "Japan","United Kingdom", "France")

#Creamos un nuevo df con las variables que necesitamos para el gráfico
paises <- data %>% 
  filter(location %in% paises) %>%
  group_by(location, date) %>% 
  summarise(muertes = new_deaths_smoothed_per_million) 
  
#Una df distinta para después agregar el grosor de linea
Spain <- data %>% 
  filter(location == "Spain") %>%
  group_by(location, date) %>% 
  summarise(muertes = new_deaths_smoothed_per_million) 

```




**Gráfico**
Creamos el grafico con la librería 'ggplot2'

```{r Gráfico}
#Primero creamos un vector con los colores que vamos a utilizar
colores <- c("Spain"="red2","Italy" = "cyan4",
              "Germany" = "palegreen4",
             "Canada" = "orangered4", "Japan" = "skyblue4", 
             "United Kingdom" = "maroon", "France" = "sienna",
             "United States" = "darkorchid4")

#Ponemos las fuentes de texto que vamos a utilizar
## Loading Google fonts (https://fonts.google.com/)
font_add_google("Roboto", "Roboto")
font_add_google("EB Garamond", "gara")

showtext_auto()


#Creamos el gráfico
graf <- ggplot(paises, aes(x = date,y = muertes, color = location)) +
  geom_line() + geom_line(mapping = aes(x = date, y = muertes),
                          colour = "red2", data = Spain, linewidth = 1 ) +
  scale_colour_manual(values = colores) + 
  labs(title = "Grupo T
Daily new confirmed COVID-19 deaths per million people", 
       subtitle = "7-day rolling average. For some countries the number of confirmed deaths is much lower than the true number of deaths. This is because of limited
testing and challenges in the attribution of the couse of death.",
x = NULL, y = NULL, 
caption = "Source:Johns Hopkins University CSSE COVID-19 Data") + 
  scale_y_continuous(breaks = seq(0,20,2)) +
  theme(plot.title = element_text(size = 15, 
                                  colour = "#222222",
                                  family = "gara"),
        plot.subtitle = element_text(size = 7,
                                     colour = "#757575",
                                     family = "Roboto"),
        plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0.01,
                                    colour = "#757575",
                                    family = "gara",
                                    size = 6),
        panel.grid.major.y = element_line(colour = "grey", linetype = 2),
        panel.background = element_blank())
graf
ggsave("GraficoTema3.pdf", plot = graf)
```


**Gráfico interactivo**

```{r Grafico interactivo}
grafite <- ggplotly(graf)
grafite
```




